# Generated by Django 5.1 on 2024-11-27 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=256)),
                ('created_at', models.DateField(auto_now=True)),
                ('question_text', models.TextField()),
                ('question_url', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_content', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
                ('answer_lawyer', models.CharField(max_length=64)),
                ('answer_rate', models.FloatField(default=0)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawl_scrape.question')),
            ],
        ),
    ]
