# Generated by Django 5.1 on 2024-11-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_scrape', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
