# Generated by Django 5.1 on 2024-10-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='password',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
