# Generated by Django 5.1 on 2024-11-20 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_core', '0005_alter_rating_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=64)),
                ('question_text', models.TextField()),
                ('question_date', models.DateTimeField()),
                ('question_url', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('answer_date', models.DateTimeField()),
                ('answer_lawyer', models.CharField(max_length=64)),
                ('answer_rate', models.FloatField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_answers', to='my_core.scrapedquestion')),
            ],
        ),
    ]
